- name: Auto Configuration
  hosts: localhost
  become: true
  tasks:
    - import_tasks: tasks/shell.yml
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/software.yml
    - import_tasks: tasks/dot_files.yml
    - import_tasks: tasks/firewall.yml
