- name: clone dotfiles
  become: no
  shell: git clone https://github.com/lderequesensS/.dotfiles.git
  tags:
    - software
    - dotfiles
- name: Stow
  shell: cd /home/leo/.dotfiles && stow */
  tags:
    - software
    - dotfiles
