- name: Install ufw
  dnf: name=ufw
  tags:
    - firewall
- name: base
  shell: ufw default deny incoming && ufw default allow outgoing
  tags:
    - firewall
- name: all
  shell: ufw allow 24642/udp comment "Stardew Valley" && ufw allow 30000/tcp comment "FoundryVTT" && ufw allow 22000 comment "Syncthing" && ufw allow 21027/udp comment "Syncthing broadcast"
  tags:
    - firewall
- name: start
  shell: ufw enable
  tags:
    - firewall
