- name: Git setup email
  git_config:
    name: user.email
    scope: global
    value: "leonardo.sobarzo@protonmail.com"
  tags:
  - git
- name: Git setup name
  git_config:
    name: user.name
    scope: global
    value: "Leo"
  tags:
  - git
